#
# SPDX-License-Identifier:	GPL-2.0+
#

head-y := arch/gpt/cpu/$(CPU)/start.o

libs-y += arch/gpt/cpu/$(CPU)/
libs-y += arch/gpt/cpu/
libs-y += arch/gpt/lib/

libs-$(CONFIG_GPT_CHIP2) += arch/gpt/mach-chip2/
