#
# (C) Copyright 2016
# scxie,General Processor Technologies Inc, scxie@hxgpt.com.
#
# SPDX-License-Identifier:	GPL-2.0+
#
extra-y = start.o

obj-$(CONFIG_APIU) += apiu.o
obj-$(CONFIG_TARGET_CHIP2_EVK) += lowlevel_init.o

